# Generated by Django 6.0.3 on 2026-05-27 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_requested_date', models.DateField(blank=True, null=True)),
                ('return_verified_date', models.DateField(blank=True, null=True)),
                ('return_status', models.CharField(choices=[('none', 'No Request'), ('pending', 'Pending Return'), ('verified', 'Returned & Verified'), ('rejected', 'Return Rejected'), ('disputed', 'Disputed')], default='none', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready to Borrow'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('fulfilled', 'Fulfilled')], default='waiting', max_length=20)),
                ('notified_date', models.DateField(blank=True, null=True)),
                ('queue_position', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['reserved_date'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester_type', models.CharField(choices=[('1st_sem', '1st Semester'), ('2nd_sem', '2nd Semester'), ('summer', 'Summer')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-academic_year', 'semester_type'],
            },
        ),
    ]
