# Generated by Django 6.0.3 on 2026-05-27 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulation', '0002_initial'),
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_borrow_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library.book'),
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='circulation.loan'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='loan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_request', to='circulation.loan'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='library.book'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'semester_type')},
        ),
        migrations.AddField(
            model_name='loan',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='circulation.semester'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['paid'], name='circulation_paid_c858bf_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['member', 'paid'], name='circulation_member__cb388d_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['-issued_date'], name='circulation_issued__b97592_idx'),
        ),
        migrations.AddConstraint(
            model_name='fine',
            constraint=models.UniqueConstraint(fields=('loan',), name='unique_fine_per_loan'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['status'], name='circulation_status_31751a_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['member', 'status'], name='circulation_member__9ef0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['book', 'status'], name='circulation_book_id_836f6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='borrowrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending'])), fields=('member', 'book'), name='unique_active_borrow_request_per_member_book'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['waiting', 'ready'])), fields=('member', 'book'), name='unique_active_reservation_per_member_book'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['due_date'], name='circulation_due_dat_cde580_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['return_status'], name='circulation_return__b64ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['member', 'return_status'], name='circulation_member__c62672_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['-loan_date'], name='circulation_loan_da_574703_idx'),
        ),
    ]
